// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// EmailServiceClient is the client API for EmailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailServiceClient interface {
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type emailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailServiceClient(cc grpc.ClientConnInterface) EmailServiceClient {
	return &emailServiceClient{cc}
}

var emailServiceSendStreamDesc = &grpc.StreamDesc{
	StreamName: "Send",
}

func (c *emailServiceClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/protocol.EmailService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServiceService is the service API for EmailService service.
// Fields should be assigned to their respective handler implementations only before
// RegisterEmailServiceService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type EmailServiceService struct {
	Send func(context.Context, *SendRequest) (*EmptyResponse, error)
}

func (s *EmailServiceService) send(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/protocol.EmailService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterEmailServiceService registers a service implementation with a gRPC server.
func RegisterEmailServiceService(s grpc.ServiceRegistrar, srv *EmailServiceService) {
	srvCopy := *srv
	if srvCopy.Send == nil {
		srvCopy.Send = func(context.Context, *SendRequest) (*EmptyResponse, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "protocol.EmailService",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "Send",
				Handler:    srvCopy.send,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "protocol/email.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewEmailServiceService creates a new EmailServiceService containing the
// implemented methods of the EmailService service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewEmailServiceService(s interface{}) *EmailServiceService {
	ns := &EmailServiceService{}
	if h, ok := s.(interface {
		Send(context.Context, *SendRequest) (*EmptyResponse, error)
	}); ok {
		ns.Send = h.Send
	}
	return ns
}

// UnstableEmailServiceService is the service API for EmailService service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableEmailServiceService interface {
	Send(context.Context, *SendRequest) (*EmptyResponse, error)
}
